name: Pipeline CI/CD - Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-deploy: 
    name: Iniciando build e deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@master